# Generated by Django 3.1.1 on 2020-10-24 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 6, 14, 33, 687473, tzinfo=utc), verbose_name='ending date'),
        ),
    ]
