# Generated by Django 3.1.1 on 2020-10-21 07:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201007_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 7, 47, 10, 37741, tzinfo=utc), verbose_name='ending date'),
        ),
    ]
