# Generated by Django 3.1.1 on 2020-10-21 09:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201021_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservote',
            options={'permissions': (('can_vote', 'User can vote once'),)},
        ),
        migrations.AlterField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 9, 57, 52, 960549, tzinfo=utc), verbose_name='ending date'),
        ),
    ]
